[build]
builder = "NIXPACKS"
installCommand = "cd backend_vite_gourmand && composer install --ignore-platform-reqs"
buildCommand = "cd backend_vite_gourmand && echo 'APP_ENV=prod' > .env"

[deploy]
startCommand = "php -S 0.0.0.0:$PORT -t backend_vite_gourmand/public backend_vite_gourmand/public/index.html"
restartPolicyType = "ON_FAILURE"