# config/services.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # 1. On laisse Symfony charger tout le dossier src d'abord
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # 2. On écrase la configuration par défaut pour ce service précis
    App\Service\StatService:
        arguments:
            $mongoUri: '%env(MONGODB_URL)%'
            $mongoDb: '%env(MONGODB_DB)%'
